//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.05 at 11:38:38 AM IST 
//


package com.vishal.consumingrest.useless;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="row" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="trx_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="customer_trx_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="is_pdf_available" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="pay_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="status_trx" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="bpid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fo_cust_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="reference_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="rn_display" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="vat_display" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="prom_date_ctrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="folio_display" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="viewxml_display" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="promise_range" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="trx_date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="due_date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="amount_due_original" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="amount_due_remaining" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="invoice_currency_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="disputs_count" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="promises_count" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="promise_broken" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="bu_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="party_no" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="bill_to_site_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="email_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="extn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="telephone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="first_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="payment_term" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="folio_display_receipt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="folio_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fo_status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="num" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="rows_count" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "row",
    "rowsCount"
})
@XmlRootElement(name = "transactions_list")
public class TransactionsList {

    protected List<TransactionsList.Row> row;
    @XmlElement(name = "rows_count")
    protected byte rowsCount;

    /**
     * Gets the value of the row property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the row property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRow().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransactionsList.Row }
     * 
     * 
     */
    public List<TransactionsList.Row> getRow() {
        if (row == null) {
            row = new ArrayList<TransactionsList.Row>();
        }
        return this.row;
    }

    /**
     * Gets the value of the rowsCount property.
     * 
     */
    public byte getRowsCount() {
        return rowsCount;
    }

    /**
     * Sets the value of the rowsCount property.
     * 
     */
    public void setRowsCount(byte value) {
        this.rowsCount = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="trx_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="customer_trx_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="is_pdf_available" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="pay_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="status_trx" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="bpid" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fo_cust_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="reference_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="rn_display" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="vat_display" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="prom_date_ctrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="folio_display" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="viewxml_display" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="promise_range" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="trx_date" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="due_date" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="amount_due_original" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="amount_due_remaining" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="invoice_currency_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="disputs_count" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="promises_count" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="promise_broken" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="bu_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="party_no" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="bill_to_site_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="email_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="extn" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="telephone" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="first_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="payment_term" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="folio_display_receipt" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="folio_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fo_status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute name="num" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "trxNumber",
        "customerTrxId",
        "isPdfAvailable",
        "type",
        "payType",
        "status",
        "statusTrx",
        "bpid",
        "currency",
        "foCustNumber",
        "referenceNumber",
        "rnDisplay",
        "vatDisplay",
        "promDateCtrl",
        "folioDisplay",
        "viewxmlDisplay",
        "promiseRange",
        "trxDate",
        "dueDate",
        "amountDueOriginal",
        "amountDueRemaining",
        "invoiceCurrencyCode",
        "disputsCount",
        "promisesCount",
        "promiseBroken",
        "buCode",
        "partyNo",
        "billToSiteId",
        "emailId",
        "extn",
        "telephone",
        "firstName",
        "lastName",
        "paymentTerm",
        "folioDisplayReceipt",
        "folioNumber",
        "foStatus"
    })
    public static class Row {

        @XmlElement(name = "trx_number", required = true)
        protected String trxNumber;
        @XmlElement(name = "customer_trx_id", required = true)
        protected String customerTrxId;
        @XmlElement(name = "is_pdf_available")
        protected byte isPdfAvailable;
        @XmlElement(required = true)
        protected String type;
        @XmlElement(name = "pay_type", required = true)
        protected String payType;
        @XmlElement(required = true)
        protected String status;
        @XmlElement(name = "status_trx", required = true)
        protected String statusTrx;
        @XmlElement(required = true)
        protected String bpid;
        @XmlElement(required = true)
        protected String currency;
        @XmlElement(name = "fo_cust_number", required = true)
        protected String foCustNumber;
        @XmlElement(name = "reference_number", required = true)
        protected String referenceNumber;
        @XmlElement(name = "rn_display", required = true)
        protected String rnDisplay;
        @XmlElement(name = "vat_display", required = true)
        protected String vatDisplay;
        @XmlElement(name = "prom_date_ctrl", required = true)
        protected String promDateCtrl;
        @XmlElement(name = "folio_display", required = true)
        protected String folioDisplay;
        @XmlElement(name = "viewxml_display", required = true)
        protected String viewxmlDisplay;
        @XmlElement(name = "promise_range")
        protected short promiseRange;
        @XmlElement(name = "trx_date", required = true)
        protected String trxDate;
        @XmlElement(name = "due_date", required = true)
        protected String dueDate;
        @XmlElement(name = "amount_due_original")
        protected float amountDueOriginal;
        @XmlElement(name = "amount_due_remaining")
        protected float amountDueRemaining;
        @XmlElement(name = "invoice_currency_code", required = true)
        protected String invoiceCurrencyCode;
        @XmlElement(name = "disputs_count")
        protected byte disputsCount;
        @XmlElement(name = "promises_count")
        protected byte promisesCount;
        @XmlElement(name = "promise_broken")
        protected byte promiseBroken;
        @XmlElement(name = "bu_code", required = true)
        protected String buCode;
        @XmlElement(name = "party_no")
        protected int partyNo;
        @XmlElement(name = "bill_to_site_id", required = true)
        protected String billToSiteId;
        @XmlElement(name = "email_id", required = true)
        protected String emailId;
        @XmlElement(required = true)
        protected String extn;
        @XmlElement(required = true)
        protected String telephone;
        @XmlElement(name = "first_name", required = true)
        protected String firstName;
        @XmlElement(name = "last_name", required = true)
        protected String lastName;
        @XmlElement(name = "payment_term", required = true)
        protected String paymentTerm;
        @XmlElement(name = "folio_display_receipt", required = true)
        protected String folioDisplayReceipt;
        @XmlElement(name = "folio_number", required = true)
        protected String folioNumber;
        @XmlElement(name = "fo_status", required = true)
        protected String foStatus;
        @XmlAttribute(name = "num")
        protected Byte num;

        /**
         * Gets the value of the trxNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTrxNumber() {
            return trxNumber;
        }

        /**
         * Sets the value of the trxNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTrxNumber(String value) {
            this.trxNumber = value;
        }

        /**
         * Gets the value of the customerTrxId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustomerTrxId() {
            return customerTrxId;
        }

        /**
         * Sets the value of the customerTrxId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustomerTrxId(String value) {
            this.customerTrxId = value;
        }

        /**
         * Gets the value of the isPdfAvailable property.
         * 
         */
        public byte getIsPdfAvailable() {
            return isPdfAvailable;
        }

        /**
         * Sets the value of the isPdfAvailable property.
         * 
         */
        public void setIsPdfAvailable(byte value) {
            this.isPdfAvailable = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the payType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPayType() {
            return payType;
        }

        /**
         * Sets the value of the payType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPayType(String value) {
            this.payType = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the statusTrx property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatusTrx() {
            return statusTrx;
        }

        /**
         * Sets the value of the statusTrx property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatusTrx(String value) {
            this.statusTrx = value;
        }

        /**
         * Gets the value of the bpid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBpid() {
            return bpid;
        }

        /**
         * Sets the value of the bpid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBpid(String value) {
            this.bpid = value;
        }

        /**
         * Gets the value of the currency property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCurrency() {
            return currency;
        }

        /**
         * Sets the value of the currency property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCurrency(String value) {
            this.currency = value;
        }

        /**
         * Gets the value of the foCustNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFoCustNumber() {
            return foCustNumber;
        }

        /**
         * Sets the value of the foCustNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFoCustNumber(String value) {
            this.foCustNumber = value;
        }

        /**
         * Gets the value of the referenceNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReferenceNumber() {
            return referenceNumber;
        }

        /**
         * Sets the value of the referenceNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReferenceNumber(String value) {
            this.referenceNumber = value;
        }

        /**
         * Gets the value of the rnDisplay property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRnDisplay() {
            return rnDisplay;
        }

        /**
         * Sets the value of the rnDisplay property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRnDisplay(String value) {
            this.rnDisplay = value;
        }

        /**
         * Gets the value of the vatDisplay property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVatDisplay() {
            return vatDisplay;
        }

        /**
         * Sets the value of the vatDisplay property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVatDisplay(String value) {
            this.vatDisplay = value;
        }

        /**
         * Gets the value of the promDateCtrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPromDateCtrl() {
            return promDateCtrl;
        }

        /**
         * Sets the value of the promDateCtrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPromDateCtrl(String value) {
            this.promDateCtrl = value;
        }

        /**
         * Gets the value of the folioDisplay property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFolioDisplay() {
            return folioDisplay;
        }

        /**
         * Sets the value of the folioDisplay property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFolioDisplay(String value) {
            this.folioDisplay = value;
        }

        /**
         * Gets the value of the viewxmlDisplay property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getViewxmlDisplay() {
            return viewxmlDisplay;
        }

        /**
         * Sets the value of the viewxmlDisplay property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setViewxmlDisplay(String value) {
            this.viewxmlDisplay = value;
        }

        /**
         * Gets the value of the promiseRange property.
         * 
         */
        public short getPromiseRange() {
            return promiseRange;
        }

        /**
         * Sets the value of the promiseRange property.
         * 
         */
        public void setPromiseRange(short value) {
            this.promiseRange = value;
        }

        /**
         * Gets the value of the trxDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTrxDate() {
            return trxDate;
        }

        /**
         * Sets the value of the trxDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTrxDate(String value) {
            this.trxDate = value;
        }

        /**
         * Gets the value of the dueDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDueDate() {
            return dueDate;
        }

        /**
         * Sets the value of the dueDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDueDate(String value) {
            this.dueDate = value;
        }

        /**
         * Gets the value of the amountDueOriginal property.
         * 
         */
        public float getAmountDueOriginal() {
            return amountDueOriginal;
        }

        /**
         * Sets the value of the amountDueOriginal property.
         * 
         */
        public void setAmountDueOriginal(float value) {
            this.amountDueOriginal = value;
        }

        /**
         * Gets the value of the amountDueRemaining property.
         * 
         */
        public float getAmountDueRemaining() {
            return amountDueRemaining;
        }

        /**
         * Sets the value of the amountDueRemaining property.
         * 
         */
        public void setAmountDueRemaining(float value) {
            this.amountDueRemaining = value;
        }

        /**
         * Gets the value of the invoiceCurrencyCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInvoiceCurrencyCode() {
            return invoiceCurrencyCode;
        }

        /**
         * Sets the value of the invoiceCurrencyCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInvoiceCurrencyCode(String value) {
            this.invoiceCurrencyCode = value;
        }

        /**
         * Gets the value of the disputsCount property.
         * 
         */
        public byte getDisputsCount() {
            return disputsCount;
        }

        /**
         * Sets the value of the disputsCount property.
         * 
         */
        public void setDisputsCount(byte value) {
            this.disputsCount = value;
        }

        /**
         * Gets the value of the promisesCount property.
         * 
         */
        public byte getPromisesCount() {
            return promisesCount;
        }

        /**
         * Sets the value of the promisesCount property.
         * 
         */
        public void setPromisesCount(byte value) {
            this.promisesCount = value;
        }

        /**
         * Gets the value of the promiseBroken property.
         * 
         */
        public byte getPromiseBroken() {
            return promiseBroken;
        }

        /**
         * Sets the value of the promiseBroken property.
         * 
         */
        public void setPromiseBroken(byte value) {
            this.promiseBroken = value;
        }

        /**
         * Gets the value of the buCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBuCode() {
            return buCode;
        }

        /**
         * Sets the value of the buCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBuCode(String value) {
            this.buCode = value;
        }

        /**
         * Gets the value of the partyNo property.
         * 
         */
        public int getPartyNo() {
            return partyNo;
        }

        /**
         * Sets the value of the partyNo property.
         * 
         */
        public void setPartyNo(int value) {
            this.partyNo = value;
        }

        /**
         * Gets the value of the billToSiteId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBillToSiteId() {
            return billToSiteId;
        }

        /**
         * Sets the value of the billToSiteId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBillToSiteId(String value) {
            this.billToSiteId = value;
        }

        /**
         * Gets the value of the emailId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmailId() {
            return emailId;
        }

        /**
         * Sets the value of the emailId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmailId(String value) {
            this.emailId = value;
        }

        /**
         * Gets the value of the extn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExtn() {
            return extn;
        }

        /**
         * Sets the value of the extn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExtn(String value) {
            this.extn = value;
        }

        /**
         * Gets the value of the telephone property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTelephone() {
            return telephone;
        }

        /**
         * Sets the value of the telephone property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTelephone(String value) {
            this.telephone = value;
        }

        /**
         * Gets the value of the firstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFirstName() {
            return firstName;
        }

        /**
         * Sets the value of the firstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFirstName(String value) {
            this.firstName = value;
        }

        /**
         * Gets the value of the lastName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastName() {
            return lastName;
        }

        /**
         * Sets the value of the lastName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastName(String value) {
            this.lastName = value;
        }

        /**
         * Gets the value of the paymentTerm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPaymentTerm() {
            return paymentTerm;
        }

        /**
         * Sets the value of the paymentTerm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPaymentTerm(String value) {
            this.paymentTerm = value;
        }

        /**
         * Gets the value of the folioDisplayReceipt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFolioDisplayReceipt() {
            return folioDisplayReceipt;
        }

        /**
         * Sets the value of the folioDisplayReceipt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFolioDisplayReceipt(String value) {
            this.folioDisplayReceipt = value;
        }

        /**
         * Gets the value of the folioNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFolioNumber() {
            return folioNumber;
        }

        /**
         * Sets the value of the folioNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFolioNumber(String value) {
            this.folioNumber = value;
        }

        /**
         * Gets the value of the foStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFoStatus() {
            return foStatus;
        }

        /**
         * Sets the value of the foStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFoStatus(String value) {
            this.foStatus = value;
        }

        /**
         * Gets the value of the num property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getNum() {
            return num;
        }

        /**
         * Sets the value of the num property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setNum(Byte value) {
            this.num = value;
        }

    }

}
